### ISSUE TITLE
undefined method `each' for "riemann-dash":String

### ISSUE THREAD

**Issue by bscott** [russellwhitaker/riemann#2]
Under CentOS 6.5

       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/riemann_wrapper/recipes/server.rb
       ================================================================================

       NoMethodError
       -------------
       undefined method `each' for "riemann-dash":String

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/riemann/recipes/dash.rb:10:in `from_file'
         /tmp/kitchen/cache/cookbooks/riemann_wrapper/recipes/server.rb:3:in `from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/riemann/recipes/dash.rb:

         3:  # Recipe:: dash
         4:  #
         5:  #
         6:
         7:  include_recipe "riemann::server"
         8:  include_recipe "riemann::client"
         9:
        10>> %{riemann-dash}.each do |pkg|
        11:    gem_package pkg do
        12:      action [:install]
        13:    end
        14:  end
        15:

**Comment by bscott** [comment]
Looking at the source at https://github.com/jjasghar/riemann/blob/master/recipes/dash.rb#L10, it seems this fix was not published to SuperMarket.

**Comment by jjasghar** [comment]
@bscott you know i love you, adding you now ;)

**Comment by jjasghar** [comment]
I had actually forgotten i had written this cookbook..... @bscott do you want it? I can transfer it to you.

**Comment by russellwhitaker** [comment]
@jjasghar if @bscott doesn't want it, I'd be very happy to take this cookbook. Please let me know: I have a pull request in to this repo for a bump in Riemann version from 0.2.0 to 0.2.9.

**Comment by jjasghar** [comment]
@russellwhitaker awesome! Yeah i'll transfer it to you now.

**Comment by jjasghar** [comment]
boo, it looks like you'll need to change your riemann repo name: russellwhitaker/riemann already exists

**Comment by russellwhitaker** [comment]
@jjasghar how about I delete russellwhitaker/riemann instead?

**Comment by jjasghar** [comment]
Sure that works too.

**Comment by russellwhitaker** [comment]
Relatedly, my supermarket.chef.io account name is 'russell_whitaker'

**Comment by russellwhitaker** [comment]
OK, you can transfer to github 'russellwhitaker' now.

**Comment by russellwhitaker** [comment]
Thanks for the transfer @jjasghar . @bscott : my reading of this issue is that is was resolved, so I'm closing it.
